### ISSUE TITLE
pos/neg examples must be on a single line, otherwise Popper is confused

### ISSUE THREAD

**Issue by hakank** [logic-and-learning-lab/Popper#10]
If the positive and negative examples in exs.pl are not each in a single line, Popper get confused.

Here's an example of this. I changed the exs.pl from examples/length example by splitting each of the pos's and neg's into two lines:
```
pos(f([3,3,1],
      3)).
pos(f([4],
      1)).
pos(f([4,3],
      2)).
pos(f([4,3,2,2,3,5,2,7],
      8)).
neg(f([3,3,1],
      2)).
neg(f([4],
      0)).
neg(f([4],
      2)).
```

This is a silly example, but for longer lines it's not unreasonable for a user to split the lines. 

As a result Popper give the first program as a solution:
```
Program 1:
f(A,B) :- empty(A),one(B).
TP: 0, FN: 0, TN: 0, FP: 0

f(A,B) :- empty(A),one(B).
```

It's 0's for TP and TN, which is weird. The culprit is in popper/tester.py where the method load_basic/1 reads the exs.pl file:
```
        # Read example file
        with open(kbpath + 'exs.pl') as f:
            for line in f:
               # ...
```

The for loop slurps the examples line by line which explains the behavior. It's a little surprising that there's no error when asserting the incomplete examples to Prolog.

Since I'm an old Perl program, regular expressions to the rescue. :-)
In  the program 
    http://hakank.org/popper/exs_with_splitlines.py  
I do some tests on a regex approach that seems to solves these issues. Here's the regex used:
    `r'(^[\s%]*(?:pos|neg)\([^\.]+?\)\.\s*)'`

The program tests for both splitted lines as well as comments in the lines and works for the test cases, but using regexes for this is error prone and might not be the best idea. It might be better to check with some sort of a grammar.

Here's a suggestion to fix tester.py using this regex approach, but I have not tested it extensively.
```
diff --git a/popper/tester.py b/popper/tester.py
index 4a9c0ad..8942b39 100644
--- a/popper/tester.py
+++ b/popper/tester.py
@@ -21,17 +21,22 @@ class Tester():
         self.prolog.consult(os.path.dirname(os.path.realpath(sys.argv[0])) + '/popper/test.pl')
 
         # Read example file
+        regexp = r'(^[\s%]*(?:pos|neg)\([^\.]+?\)\.\s*)'
+        flags = re.M
         with open(kbpath + 'exs.pl') as f:
-            for line in f:
-                if line.startswith('%'):
-                    continue
-                # Assert negative and positive examples
-                for x in re.findall("pos\((.*)\)\.", line):
-                    self.prolog.assertz(f'pos({x})')
-                    self.num_pos += 1
-                for x in re.findall("neg\((.*)\)\.", line):
-                    self.prolog.assertz(f'neg({x})')
-                    self.num_neg += 1
+            slurp = f.read().replace("\n"," ")
+            lines = [x.group() for x in re.finditer(regexp, slurp,flags=flags)]
+            # remove commented lines
+            lines = [line for line in lines if not line.startswith('%')]
+            pos = [line for line in lines if line.startswith('pos(')]
+            for x in pos:
+                self.prolog.assertz(x.replace(".",""))
+            neg = [line for line in lines if line.startswith('neg(')]
+            for x in neg:
+                self.prolog.assertz(x.replace(".",""))
+
+            self.num_pos = len(pos)
+            self.num_neg = len(neg)            
 
         self.prolog.assertz(f'num_pos({self.num_pos})')
         self.prolog.assertz(f'num_neg({self.num_neg})')
```

However, perhaps it might be better to simply state that each pos/neg must be written on a single line.

**Comment by hakank** [comment]
However, this regexp approach just works for very simple exs.pl without any longer comments

**Comment by rolfmorel** [comment]
Thanks for reporting this, Hakan.

We have fixed it by just letting SWI do the parsing of `exs.pl`. Popper should now accept examples written as any valid Prolog code.

**Comment by hakank** [comment]
Sorry about opening this again but if the `exs.pl` file not don't contain any `neg/1` examples then the following error occur:
```
Process Process-1:
Traceback (most recent call last):
  File "/home/hakank/anaconda3/envs/potassco/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hakank/anaconda3/envs/potassco/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper.py", line 31, in popper
    tester = Tester(experiment)
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper/tester.py", line 16, in __init__
    self.load_basic(experiment.args.kbpath)
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper/tester.py", line 35, in load_basic
    self.num_neg = sum(1 for _ in self.prolog.query('neg(_)'))
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper/tester.py", line 35, in <genexpr>
    self.num_neg = sum(1 for _ in self.prolog.query('neg(_)'))
  File "/home/hakank/anaconda3/envs/potassco/lib/python3.9/site-packages/pyswip/prolog.py", line 126, in __call__
    raise PrologError("".join(["Caused by: '", query, "'. ",
pyswip.prolog.PrologError: Caused by: 'neg(_)'. Returned: 'error(existence_error(procedure, /(neg, 1)), context(/(pyrun, 2), _40))'.

```

**Comment by rolfmorel** [comment]
Thanks, that was indeed an oversight on my part.

The above commit should now deal with it properly.

**Comment by hakank** [comment]
Thanks. It works now.
