### ISSUE TITLE
The new --info flag sometimes throws ZeroDivisionError 

### ISSUE THREAD

**Issue by hakank** [logic-and-learning-lab/Popper#18]
The new `--info` flag sometimes throws `ZeroDivisionError: division by zero` . For example running example/dropk:

```
$ time popper.py --info  examples/dropk 
NEW BEST PROG 1:
f(A,B,C):-tail(A,C),head(C,B)
Traceback (most recent call last):
  File "popper.py", line 197, in <module>
    timeout(popper, (settings, stats, args), timeout_duration=int(settings.timeout))
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper/util.py", line 43, in timeout
    result = func(*args, **kwargs)
  File "popper.py", line 175, in popper
    print_conf_matrix(conf_matrix)
  File "popper.py", line 128, in print_conf_matrix
    precision = tp / (tp+fp)
ZeroDivisionError: division by zero
```

I like the new flag by the way; it's neater than running with `--debug`.

**Comment by andrewcropper** [comment]
Fixed! Thank you very much for spotting the bug!
