### ISSUE TITLE
ERROR: Syntax error: Operator expected

### ISSUE THREAD

**Issue by hakank** [logic-and-learning-lab/Popper#23]
When running some of the examples, e.g. `examples/reverse`, the following error is thrown:

```
$ popper.py --info examples/reverse
ERROR: Syntax error: Operator expected
ERROR: assertz((pos_index(3,f([Ato
ERROR: ** here **
ERROR: m('324485'), Atom('443525'), Atom('544261')], [Atom('544261'), Atom('443525'), Atom('324485')])))). 
Traceback (most recent call last):
  File "popper.py", line 180, in <module>
    timeout(popper, (settings, stats), timeout_duration=int(settings.timeout))
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper/util.py", line 51, in timeout
    result = func(*args, **kwargs)
  File "popper.py", line 122, in popper
    tester = Tester(settings)
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper/tester.py", line 17, in __init__
    self.load_basic()
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper/tester.py", line 52, in load_basic
    self.load_examples()
  File "/home/hakank/inductive_programming/andrewcropper/popper/Popper/popper/tester.py", line 36, in load_examples
    self.prolog.assertz(f'pos_index({i},{x})')
  File "/usr/local/lib/python3.7/site-packages/pyswip-0.2.10-py3.7.egg/pyswip/prolog.py", line 152, in assertz
  File "/usr/local/lib/python3.7/site-packages/pyswip-0.2.10-py3.7.egg/pyswip/prolog.py", line 129, in __call__
pyswip.prolog.PrologError: Caused by: 'assertz((pos_index(3,f([Atom('324485'), Atom('443525'), Atom('544261')], [Atom('544261'), Atom('443525'), Atom('324485')])))).'. Returned: 'error(syntax_error(operator_expected), string(b"assertz((pos_index(3,f([Atom('324485'), Atom('443525'), Atom('544261')], [Atom('544261'), Atom('443525'), Atom('324485')])))). ", 27))'.
```

I **think** it's a very recent error since I'm quite sure I tested all the examples some days ago without any problems.

**Comment by andrewcropper** [comment]
Thank you @hakank for spotting this silly bug that I recently introduced. This commit should fix it https://github.com/logic-and-learning-lab/Popper/commit/87b0a3551ea2de82ce9a7255d2b6d935041308a1
